language: "Arduino"
before_install:
	- sudo apt-get update
install:
	- sudo apt-get install picocom
	- git clone git://github.com/amperka/ino.git
	- make install
	- pip install ino
script:
	- ino build
branches:
  only:
    - master