language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install picocom
  - git clone git://github.com/amperka/ino.git
  - cd ino
  - make install
  - pip install ino
script:
  - ino build
branches:
  only:
    - master
