language: c
install:
  - sudo apt-get update -qq
  - sudo apt-get install python-setuptools python-pip
  - sudo apt-get install arduino arduino-core picocom
  - git clone git://github.com/amperka/ino.git
  - cd ino
  - sudo make install
  - sudo pip install ino
  - cd ..
script:
  - ino build
branches:
  only:
    - master
